/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AddRouteImport } from './routes/add'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CellarRouteImport } from './routes/cellar'
import { Route as PairRouteImport } from './routes/pair'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as UploadLogoRouteImport } from './routes/upload-logo'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as WineIdRouteImport } from './routes/wine/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AddRoute = AddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CellarRoute = CellarRouteImport.update({
  id: '/cellar',
  path: '/cellar',
  getParentRoute: () => rootRouteImport,
} as any)
const PairRoute = PairRouteImport.update({
  id: '/pair',
  path: '/pair',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadLogoRoute = UploadLogoRouteImport.update({
  id: '/upload-logo',
  path: '/upload-logo',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const WineIdRoute = WineIdRouteImport.update({
  id: '/wine/$id',
  path: '/wine/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/auth': typeof AuthRoute
  '/cellar': typeof CellarRoute
  '/pair': typeof PairRoute
  '/profile': typeof ProfileRoute
  '/upload-logo': typeof UploadLogoRoute
  '/wishlist': typeof WishlistRoute
  '/wine/$id': typeof WineIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/auth': typeof AuthRoute
  '/cellar': typeof CellarRoute
  '/pair': typeof PairRoute
  '/profile': typeof ProfileRoute
  '/upload-logo': typeof UploadLogoRoute
  '/wishlist': typeof WishlistRoute
  '/wine/$id': typeof WineIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/auth': typeof AuthRoute
  '/cellar': typeof CellarRoute
  '/pair': typeof PairRoute
  '/profile': typeof ProfileRoute
  '/upload-logo': typeof UploadLogoRoute
  '/wishlist': typeof WishlistRoute
  '/wine/$id': typeof WineIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add'
    | '/auth'
    | '/cellar'
    | '/pair'
    | '/profile'
    | '/upload-logo'
    | '/wishlist'
    | '/wine/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add'
    | '/auth'
    | '/cellar'
    | '/pair'
    | '/profile'
    | '/upload-logo'
    | '/wishlist'
    | '/wine/$id'
  id:
    | '__root__'
    | '/'
    | '/add'
    | '/auth'
    | '/cellar'
    | '/pair'
    | '/profile'
    | '/upload-logo'
    | '/wishlist'
    | '/wine/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddRoute: typeof AddRoute
  AuthRoute: typeof AuthRoute
  CellarRoute: typeof CellarRoute
  PairRoute: typeof PairRoute
  ProfileRoute: typeof ProfileRoute
  UploadLogoRoute: typeof UploadLogoRoute
  WishlistRoute: typeof WishlistRoute
  WineIdRoute: typeof WineIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add': {
      id: '/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cellar': {
      id: '/cellar'
      path: '/cellar'
      fullPath: '/cellar'
      preLoaderRoute: typeof CellarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pair': {
      id: '/pair'
      path: '/pair'
      fullPath: '/pair'
      preLoaderRoute: typeof PairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload-logo': {
      id: '/upload-logo'
      path: '/upload-logo'
      fullPath: '/upload-logo'
      preLoaderRoute: typeof UploadLogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wine/$id': {
      id: '/wine/$id'
      path: '/wine/$id'
      fullPath: '/wine/$id'
      preLoaderRoute: typeof WineIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddRoute: AddRoute,
  AuthRoute: AuthRoute,
  CellarRoute: CellarRoute,
  PairRoute: PairRoute,
  ProfileRoute: ProfileRoute,
  UploadLogoRoute: UploadLogoRoute,
  WishlistRoute: WishlistRoute,
  WineIdRoute: WineIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
